service: metadata-scraping-service
plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  environment:
    REGION: us-east-1
    TABLE_NAME: metadata
    # DAX_ENDPOINT: daxs://dax-cluster-******.dax-clusters.us-east-1.amazonaws.com

functions:
  metadataScappingService:
    handler: functions/scrapper.getMetadata
    timeout: 60
    layers:
      - { Ref: CommonLibsLambdaLayer }
    memorySize: 512
    description: Submit URL to get metadata for that URL
    # vpc:
    #   securityGroupIds:
    #     - sg-3*****5
    #   subnetIds:
    #     - subnet-2****f
    #     - subnet-3****d
    #     - subnet-5****b
    events:
      - http:
          path: /metadata
          method: post
          cors: true
          caching:
            enabled: true
            ttlInSeconds: 300
            dataEncrypted: false
            perKeyInvalidation:
              requireAuthorization: false
              handleUnauthorizedRequests: IgnoreWithWarning
            cacheKeyParameters:
              - name: request.path.pawId
              - name: request.header.Accept-Language

layers:
  commonLibs:
    path: layers
    compatibleRuntimes:
      - nodejs14.x

resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: metadata
        AttributeDefinitions:
          - AttributeName: url
            AttributeType: S
        KeySchema:
          - AttributeName: url
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
    DynamoDBIamPolicy:
      Type: AWS::IAM::Policy
      DependsOn: DynamoDbTable
      Properties:
        PolicyName: lambda-dynamodb
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
              Resource: arn:aws:dynamodb:*:*:table/metadata
        Roles:
          - Ref: IamRoleLambdaExecution
